### ISSUE TITLE
Encoder::encode_to_string() is infallible

### ISSUE THREAD

**Issue by niklasf** [jedisct1/rust-ct-codecs#2]
`Encoder::encode_to_string()` currently returns `Result<String, ct_codecs::Error>`, but can never actually error:

* For *encoding*, all inputs are valid
* The allocated buffer will be as large as needed

Could be changed to unwrap internally, in a future version 2.0.0.

**Comment by jedisct1** [comment]
It doesn't in the current implementation. The graceful way to handle out of bounds errors (for example because the output would exceed usize::max) is currently to panic, which is the idiomatic Rust way, but we could do much better. Applications are encouraged to check that error. If it doesn't do anything, it will be optimized out anyway.
I'd also like to avoid breaking changes that are not strictly necessary.

**Comment by niklasf** [comment]
I see. On 32-bit systems it's certainly possible even today, so I was just wrong.

**Comment by jedisct1** [comment]
I just took a look at the code, and it *is* faillible. `encoded_len()` can return an `Error:Overflow` error.
